### ISSUE TITLE
Line break for welcome message

### ISSUE THREAD

**Issue by haoxue-fan** [gouverneurp/eVAS#1]
Hi @gouverneurp ! I tried out the eVAS Mac standalone app (which has been great!) and played around with the configuration. I cannot figure out a way to insert multiple lines/insert line break for the welcome message (it seems will just go over the border of the app). I consider this feature could be useful since sometimes researchers may have relatively lengthy prompt or want more customization. Is there anyway we can enable this feature?

**Comment by gouverneurp** [comment]
Hi @haoxue-fan!
Thank you for your valuable feedback! We are glad that you like eVAS.

I really enjoy your comments as they bring up nice features that we obviously had not thought of.

Regarding a multi-line welcome message: 
What do you think of the following [change](https://github.com/gouverneurp/eVAS/commit/5834be1b4feddb183a31174e4dae21fb20ee67b9)?
Instead of giving a simple message text, users can now give a list of strings as welcome message. 
Each item is displayed on a separate line.

What do you think? Or is the list too complicated?

By the way, building the application on Mac and checking for Mac related issues is time consuming for me as I build on a virtual machine. I will need some time to check everything Mac related.
Also, I would like to build a new version for GitHub (and the automatic update) only from time to time as I have to build it for 3 operating systems.

**Comment by haoxue-fan** [comment]
Hey @gouverneurp thanks for the quick reply! I think the fix looks great and is pretty intuitive. Thanks a lot! 

And yeah I can totally understand (and respect) the amount of effort required to build the apps. If any of my comments you feel 'this is too much'/'i dont know whether I will prioritize this for now' just feel free to comment to let me know - i was just trying to jog down all the thoughts i have to help improve the usability :)

**Comment by gouverneurp** [comment]
@ haoxue-fan, thank you!
I will let you know! Moreover, I will have a look for **all** the issues. 
Just wanted to point out that I will need more time for Mac related problems (I am using Windows and Linux) and that releases on GitHub will be from time to time.

Do you think I should then close issues when they are fixed?
How does it usually work with JOSS?
Do you consider this one as "fixed"?

**Comment by haoxue-fan** [comment]
I will consider this as fixed and I can close it with comments! JOSS is pretty flexible - moving forward I think either the reviewer or the author could close the issue as long as both parties are satisfied (and can also re-open it if new stuff comes up) :D

**Comment by haoxue-fan** [comment]
(p.s. I have also seen people adding tag for the issues related to reviewing process (e.g., [here](https://github.com/ihrke/pypillometry/issues?q=is%3Aissue+is%3Aclosed)) Not necessary, but just putting it here in case you are looking for some past review examples :)
